import Document, { Html, Head, Main, NextScript } from "next/document";

export default class CustomDocument extends Document {
    render() {
        return (
            <Html lang="en">
                <Head>
                    <link
                        rel="icon"
                        sizes="52x52"
                        href="/images/favicons-safari/apple-touch-icon-52x52.png"
                        type="image/png"
                    />
                    <link
                        rel="shortcut icon"
                        type="image/png"
                        href="/images/favicons-safari/favicon-16x16.png"
                        sizes="16x16"
                    />
                    <link
                        rel="mask-icon"
                        href="/images/favicons-safari/apple-touch-icon-52x52.png"
                        color="#000000"
                        type="image/png"
                        sizes="52x52"
                    />

                    {/* ICONS FOR SAFARI BROWSER TAB START */}
                    <link
                        rel="apple-touch-icon"
                        sizes="57x57"
                        href="/images/favicons-safari/apple-touch-icon-57x57.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="114x114"
                        href="/images/favicons-safari/apple-touch-icon-114x114.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="72x72"
                        href="/images/favicons-safari/apple-touch-icon-72x72.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="144x144"
                        href="/images/favicons-safari/apple-touch-icon-144x144.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="60x60"
                        href="/images/favicons-safari/apple-touch-icon-60x60.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="120x120"
                        href="/images/favicons-safari/apple-touch-icon-120x120.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="76x76"
                        href="/images/favicons-safari/apple-touch-icon-76x76.png"
                        type="image/png"
                    />
                    <link
                        rel="apple-touch-icon"
                        sizes="152x152"
                        href="/images/favicons-safari/apple-touch-icon-152x152.png"
                        type="image/png"
                    />
                    {/* ICONS FOR SAFARI BROWSER TAB END */}

                    <meta name="description" content="Generated by create next app" />

                    <script src="https://accounts.google.com/gsi/client" async defer></script>
                    <script src="https://www.gstatic.com/firebasejs/9.8.3/firebase-app-compat.js" async defer></script>
                    <script src="https://www.gstatic.com/firebasejs/9.8.3/firebase-messaging-compat.js" async defer></script>
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
    }
}